### PR TITLE
Simplify

### PR DESCRIPTION
**Pull request by RayStick**

### CODE REVIEW

**Comment by RayStick** [comment]
Hi @kristinazvolanek, this is a really simple update, mostly just to the README file (as this is publicly available code). Thanks in advance!

**Review by kristinazvolanek — APPROVED** [review]
I didn't test locally, but minor changes look good to me!

**Comment by RayStick** [comment]
@all-contributors please add @kristinazvolanek for pull request review

**Comment by RayStick** [comment]
@all-contributors please add @kristinazvolanek for pull request review

**Comment by RayStick** [comment]
https://github.com/all-contributors please add @kristinazvolanek for pull request review and ideas

**Pull request merged**
