### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RayStick**
Really simple change to README.md

### CODE REVIEW

**Review by kristinazvolanek — APPROVED** [review]
LGTM!

**Comment by RayStick** [comment]
@all-contributors please add @kristinazvolanek for pull request review and ideas

**Comment by RayStick** [comment]
@all-contributors add @RayStick for code, ideas and documentation, and add @kristinazvolanek for ideas and pull request reviews

**Comment by RayStick** [comment]
@all-contributors add @RayStick for code, ideas and documentation

**Comment by RayStick** [comment]
@all-contributors add @kristinazvolanek for ideas and pull request reviews

**Comment by RayStick** [comment]
@all-contributors add @BrightMG for ideas

**Comment by RayStick** [comment]
@all-contributors add @smoia  for ideas

**Comment by RayStick** [comment]
@all-contributors add @CesarCaballeroGaudes for ideas

**Pull request merged**
